"""Switch to full name over single names, update Services enums

Revision ID: 6f31241a48d8
Revises: 4a7a409a2542
Create Date: 2025-01-01 18:01:13.517988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f31241a48d8'
down_revision = '4a7a409a2542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.String(length=30), nullable=False))
        batch_op.drop_column('l_name')
        batch_op.drop_column('f_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('f_name', mysql.VARCHAR(length=30), nullable=False))
        batch_op.add_column(sa.Column('l_name', mysql.VARCHAR(length=30), nullable=False))
        batch_op.drop_column('fullname')

    # ### end Alembic commands ###
