"""change services to json blob, remove relationships.

Revision ID: 9bd0faf70ec8
Revises: 47b2f584912a
Create Date: 2025-01-02 19:32:46.163964

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9bd0faf70ec8'
down_revision = '47b2f584912a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('services', sa.JSON(), nullable=False))
        batch_op.drop_column('service')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service', mysql.VARCHAR(length=30), nullable=False))
        batch_op.drop_column('services')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
